/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppProcessKnowledgeRouteImport } from './routes/app.process-knowledge'
import { Route as AppMonitoringRouteImport } from './routes/app.monitoring'
import { Route as AppManagementRouteImport } from './routes/app.management'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppExplainRouteImport } from './routes/app.explain'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAnalyseRouteImport } from './routes/app.analyse'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessKnowledgeRoute = AppProcessKnowledgeRouteImport.update({
  id: '/process-knowledge',
  path: '/process-knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppManagementRoute = AppManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainRoute = AppExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyseRoute = AppAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analyse': typeof AppAnalyseRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explain': typeof AppExplainRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/management': typeof AppManagementRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/process-knowledge': typeof AppProcessKnowledgeRoute
  '/app/recommendations': typeof AppRecommendationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analyse': typeof AppAnalyseRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explain': typeof AppExplainRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/management': typeof AppManagementRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/process-knowledge': typeof AppProcessKnowledgeRoute
  '/app/recommendations': typeof AppRecommendationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analyse': typeof AppAnalyseRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explain': typeof AppExplainRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/management': typeof AppManagementRoute
  '/app/monitoring': typeof AppMonitoringRoute
  '/app/process-knowledge': typeof AppProcessKnowledgeRoute
  '/app/recommendations': typeof AppRecommendationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analyse'
    | '/app/dashboard'
    | '/app/explain'
    | '/app/feedback'
    | '/app/management'
    | '/app/monitoring'
    | '/app/process-knowledge'
    | '/app/recommendations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analyse'
    | '/app/dashboard'
    | '/app/explain'
    | '/app/feedback'
    | '/app/management'
    | '/app/monitoring'
    | '/app/process-knowledge'
    | '/app/recommendations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analyse'
    | '/app/dashboard'
    | '/app/explain'
    | '/app/feedback'
    | '/app/management'
    | '/app/monitoring'
    | '/app/process-knowledge'
    | '/app/recommendations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/process-knowledge': {
      id: '/app/process-knowledge'
      path: '/process-knowledge'
      fullPath: '/app/process-knowledge'
      preLoaderRoute: typeof AppProcessKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring': {
      id: '/app/monitoring'
      path: '/monitoring'
      fullPath: '/app/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/management': {
      id: '/app/management'
      path: '/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explain': {
      id: '/app/explain'
      path: '/explain'
      fullPath: '/app/explain'
      preLoaderRoute: typeof AppExplainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyse': {
      id: '/app/analyse'
      path: '/analyse'
      fullPath: '/app/analyse'
      preLoaderRoute: typeof AppAnalyseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyseRoute: typeof AppAnalyseRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExplainRoute: typeof AppExplainRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppManagementRoute: typeof AppManagementRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppProcessKnowledgeRoute: typeof AppProcessKnowledgeRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyseRoute: AppAnalyseRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExplainRoute: AppExplainRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppManagementRoute: AppManagementRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppProcessKnowledgeRoute: AppProcessKnowledgeRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
